INSERT INTO store_items (item_name, price, stock, description) VALUES
('Hoodie', 29.99, 50, 'Comfortable and warm hoodie available in various sizes and colors.'),
('T-Shirt', 19.99, 100, '100% cotton t-shirt with a variety of prints and designs.'),
('Mug', 9.99, 200, 'Ceramic mug perfect for coffee or tea, available in multiple designs.'),
('Pen', 1.99, 500, 'Smooth-writing ballpoint pen with a comfortable grip.'),
('Poster', 14.99, 150, 'High-quality poster with vibrant colors, perfect for decorating your space.'),
('Notebook', 4.99, 300, 'Spiral-bound notebook with lined pages.'),
('Water Bottle', 12.99, 180, 'Stainless steel water bottle with a leak-proof cap.'),
('Backpack', 49.99, 75, 'Durable and spacious backpack suitable for everyday use.'),
('Sticker Pack', 5.99, 400, 'Set of assorted stickers for decoration.'),
('Keychain', 3.99, 250, 'Stylish keychain with a durable ring.'),
('Cap', 24.99, 80, 'Adjustable cap with embroidered logo.'),
('Sweatpants', 34.99, 60, 'Comfortable sweatpants available in various sizes.'),
('Mouse Pad', 7.99, 150, 'Smooth surface mouse pad with non-slip base.'),
('Phone Case', 15.99, 120, 'Protective phone case available for various models.'),
('Sunglasses', 19.99, 110, 'Stylish sunglasses with UV protection.'),
('Tote Bag', 11.99, 140, 'Reusable tote bag made from eco-friendly materials.'),
('USB Drive', 8.99, 90, '16GB USB drive with a keyring attachment.'),
('Beanie', 18.99, 100, 'Warm beanie hat available in multiple colors.'),
('Lanyard', 4.99, 200, 'Durable lanyard with a detachable clip.'),
('Notebook', 6.99, 300, 'Hardcover notebook with blank pages.');
